pub const OP_SETCONST: u8 = 0;                // ptrL,  ptrH,  val
pub const OP_SETLOAD: u8 = 1;                 // dstL,  dstH,  srcL,  srcH
pub const OP_ADDASSIGN: u8 = 2;               // ptrL,  ptrH,  val
pub const OP_ADDCONST: u8 = 3;                // dstL,  dstH,  srcL,  srcH,  val
pub const OP_ADDLOAD: u8 = 4;                 // dstL,  dstH,  src1L, src1H, src2L, src2H,
pub const OP_SUBLC: u8 = 5;                   // dstL,  dstH,  srcL,  srcH,  val
pub const OP_SUBCL: u8 = 6;                   // dstL,  dstH,  val,   srcL,  srcH
pub const OP_SUBLL: u8 = 7;                   // dstL,  dstH,  src1L, src1H, src2L, src2H,
pub const OP_MULCONST: u8 = 8;                // dstL,  dstH,  srcL,  srcH,  val
pub const OP_MULLOAD: u8 = 9;                 // dstL,  dstH,  src1L, src1H, src2L, src2H,
pub const OP_MULADDCONST: u8 = 10;            // dstL,  dstH,  val,   srcL,  srcH,  val
pub const OP_MULADDLOAD: u8 = 11;             // dstL,  dstH,  src1L, src1H, src2L, src2H, val
pub const OP_IN: u8 = 12;                     // ptrL,  ptrH
pub const OP_OUTLOAD: u8 = 13;                // ptrL,  ptrH
pub const OP_OUTCONST: u8 = 14;               // val
pub const OP_JUMP: u8 = 15;                   // addr1, addr2, addr3, addr4
pub const OP_JUMPIFZERO: u8 = 16;             // ptrL,  ptrH,  addr1, addr2, addr3, addr4
pub const OP_JUMPIFNOTZERO: u8 = 17;          // ptrL,  ptrH,  addr1, addr2, addr3, addr4
pub const OP_OFFSETRANGEJUMPZERO: u8 = 18;    // ofsL,  ofsH,  rsl,   rsh,   rel,   reh,   ptrL, ptrH, addr1, addr2, addr3, addr4
pub const OP_OFFSETRANGEJUMPNOTZERO: u8 = 19; // ofsL,  ofsH,  rsl,   rsh,   rel,   reh,   ptrL, ptrH, addr1, addr2, addr3, addr4
pub const OP_OFFSET: u8 = 20;                 // ofsL,  ofsH
pub const OP_OFFSETWITHRANGECHECK: u8 = 21;   // ofsL,  ofsH,  rsl,   rsh,   rel,   reh,
pub const OP_FINDZERO: u8 = 22;               // ptrL,  ptrH,  ofsL,  ofsH,
pub const OP_FINDZEROWITHRANCECHECK: u8 = 23; // ptrL,  ptrH,  ofsL,  ofsH,  rsl,   rsh,   rel,  reh,
pub const OP_END: u8 = 24;
