use crate::bytecode::bytecode::Bytecode;

impl Bytecode {
    fn to_c(&self, i: i32) -> String {
        match self {
            Self::SetC(p1, c2) => format!("tape[{}] = {};", p1, c2),
            Self::SetL(p1, p2) => format!("tape[{}] = tape[{}];", p1, p2),
            Self::Add(ptr, val) => format!("tape[{}] += {};", ptr, val),
            Self::AddC(p1, p2, c3) => format!("tape[{}] = tape[{}] + {};", p1, p2, c3),
            Self::AddL(p1, p2, p3) => format!("tape[{}] = tape[{}] + tape[{}];", p1, p2, p3),
            Self::AddLA(p1, p2) => format!("tape[{}] += tape[{}];", p1, p2),
            Self::SubLC(p1, p2, c3) => format!("tape[{}] = tape[{}] - {};", p1, p2, c3),
            Self::SubCL(p1, c2, p3) => format!("tape[{}] = {} - tape[{}];", p1, c2, p3),
            Self::SubLL(p1, p2, p3) => format!("tape[{}] = tape[{}] - tape[{}];", p1, p2, p3),
            Self::MulC(p1, p2, c3) => format!("tape[{}] = tape[{}] * {};", p1, p2, c3),
            Self::MulL(p1, p2, p3) => format!("tape[{}] = tape[{}] * tape[{}];", p1, p2, p3),

            Self::MulAddC(p1, c2, p3, c4) => format!("tape[{}] = {} + tape[{}] * {};", p1, c2, p3, c4),
            Self::MulAddL(p1, p2, p3, c4) => format!("tape[{}] = tape[{}] + tape[{}] * {};", p1, p2, p3, c4),

            Self::In(p1) => format!("tape[{}] = getchar();", p1),

            Self::Out(p1) => format!("putchar(tape[{}]);", p1),
            Self::OutConst(v1) => format!("putchar({});", v1),
            Self::Jump(a1) => format!("goto n{};", a1 + i),
            Self::JumpIfZero(p1, a2) => format!("if (!tape[{}]) goto n{};", p1, a2 + i),
            Self::JumpIfNotZero(p1, a2) => format!("if (tape[{}]) goto n{};", p1, a2 + i),
            Self::Offset(o1) => format!("tape += {};", o1),
            Self::OffsetWithRangeCheck(o1, range) => format!("tape += {}; rangecheck({}, {});", o1, range.start(), range.end()),
            Self::RangeCheck(range) => format!("rangecheck({}, {});", range.start(), range.end()),
            Self::FindZero(ptr, delta) => format!("while (tape[{}]) {{ tape += {}; }}", ptr, delta),
            Self::End => "return 0;".to_string(),

            Self::SetCSetC(p1, c1, p2, c2) => format!(
                "tape[{}] = {}; tape[{}] = {};",
                p1, c1, p2, c2
            ),
            Self::AddAdd(p1, c1, p2, c2) => format!(
                "tape[{}] += {}; tape[{}] += {};",
                p1, c1, p2, c2
            ),
            Self::AddSetC(p1, c1, p2, c2) => format!(
                "tape[{}] += {}; tape[{}] = {};",
                p1, c1, p2, c2
            ),
            Self::MulAddMulAdd {
                src,
                dst1,
                dst2_rel,
                val1,
                val2,
            } => {
                let dst2 = *src + (*dst2_rel as i16);
                format!(
                    "tape[{}] += tape[{}] * {}; tape[{}] += tape[{}] * {};",
                    dst1, src, val1, dst2, src, val2
                )
            }
            Self::OutOut(p1, p2) => format!("putchar(tape[{}]); putchar(tape[{}]);", p1, p2),
        }
    }
}

pub fn bc_to_c(bytecodes: &[Bytecode], offset: u8) -> String {
    let mut body = String::new();
    for (idx, bytecode) in bytecodes.iter().enumerate() {
        body.push_str(&format!("    n{}: {}\n", idx, bytecode.to_c(idx as i32)));
    }

    format!(
        "/* generated by brainrot2 */
#include <stdlib.h>
#include <stdint.h>
#include <stdio.h>
static uint8_t main_tape[65536];
static uint8_t* tape;

void rangecheck(int start, int end) {{
    int offset = tape - &main_tape;
    if (start <= offset && offset <= end) {{
        /* okay */
    }} else {{
        /* out of bounds */
        exit(1);
    }}
}}

int main(void) {{
    tape = main_tape + {offset};
{}
    return 2;
}}
",
        body
    )
}
